//go:build windows

package main

import (
	"runtime"
	"syscall"
	"time"
	"unsafe"

	"github.com/jchv/go-webview2/pkg/edge"
	"github.com/lxn/win"
	"golang.org/x/sys/windows"

	"github.com/owaiskhanov/okbrowser/internal/nav"
)

const (
	appName   = "OK Browser"
	className = "OKBrowserMainWnd"
)

// Toolbar / child control identifiers.
const (
	idcBack    = 101
	idcForward = 102
	idcReload  = 103
	idcHome    = 104
	idcAddress = 105
	idcGo      = 106
	idcHost    = 107

	// Commands generated by the accelerator (hotkey) table.
	cmdBack         = 201
	cmdForward      = 202
	cmdReload       = 203
	cmdHome         = 204
	cmdFocusAddress = 205
	cmdNewWindow    = 206
	cmdCloseWindow  = 207
)

// Segoe MDL2 Assets glyphs - the icon font built into Windows 10+.
const (
	glyphBack    = "\uE76B" // ChevronLeft
	glyphForward = "\uE76C" // ChevronRight
	glyphReload  = "\uE72C" // Refresh
	glyphHome    = "\uE80F" // Home
	glyphGo      = "\uE721" // Search
)

// app is one browser window. OK Browser runs one window per process, which
// keeps every window responsive and feather-light.
type app struct {
	hwnd     win.HWND
	instance win.HINSTANCE
	accel    win.HACCEL

	// chromium is the embedded WebView2 engine.
	chromium *edge.Chromium

	// lastSpawn throttles popup storms: a page asking for a burst of new
	// windows gets at most a few per second.
	lastSpawn time.Time

	// isStart is true while the built-in start page is showing.
	isStart bool

	// Toolbar controls.
	back    win.HWND
	forward win.HWND
	reload  win.HWND
	home    win.HWND
	address win.HWND
	goBtn   win.HWND

	// host is the child window the WebView2 engine renders into.
	host win.HWND

	fontUI    win.HFONT // Segoe UI, address bar etc.
	fontGlyph win.HFONT // Segoe MDL2 Assets, toolbar buttons

	scale float64 // DPI scale factor (1.0 = 96 DPI)
}

// theApp is the single window of this process, reachable from wndProc.
var theApp *app

func wndProc(hwnd win.HWND, msg uint32, wp uintptr, lp unsafe.Pointer) uintptr {
	a := theApp
	if a == nil {
		return win.DefWindowProc(hwnd, msg, wp, uintptr(lp))
	}
	switch msg {
	case win.WM_CREATE:
		a.hwnd = hwnd
		return 0

	case win.WM_SIZE:
		a.layout()
		return 0

	case win.WM_GETMINMAXINFO:
		mmi := (*win.MINMAXINFO)(lp)
		mmi.PtMinTrackSize = win.POINT{X: a.scaled(560), Y: a.scaled(420)}
		return 0

	case win.WM_COMMAND:
		// Buttons send notification 0 (BN_CLICKED); the accelerator table
		// sends 1; menus send 0 (we have none).
		switch win.HIWORD(uint32(wp)) {
		case 0, 1:
			a.onCommand(int(win.LOWORD(uint32(wp))))
		}
		return 0

	case win.WM_DPICHANGED:
		a.onDpiChanged(int(win.HIWORD(uint32(wp))), (*win.RECT)(lp))
		return 0

	case win.WM_DESTROY:
		win.PostQuitMessage(0)
		return 0
	}
	return win.DefWindowProc(hwnd, msg, wp, uintptr(lp))
}

// NewApp creates the main window, embeds the web engine and navigates to the
// start page (or startURL when given). It returns false when the WebView2
// runtime is unavailable.
func NewApp(startURL string) (*app, bool) {
	// All UI and COM work stays on one OS thread, as Win32 requires.
	runtime.LockOSThread()

	a := &app{}
	a.scale = float64(dpiOf(0)) / 96.0
	theApp = a

	a.instance = win.GetModuleHandle(nil)
	icon := loadAppIcon(a.instance)
	cursor := win.LoadCursor(0, win.MAKEINTRESOURCE(win.IDC_ARROW))

	cn, err := syscall.UTF16PtrFromString(className)
	if err != nil {
		return nil, false
	}
	wc := win.WNDCLASSEX{
		CbSize:        uint32(unsafe.Sizeof(win.WNDCLASSEX{})),
		LpfnWndProc:   windows.NewCallback(wndProc),
		HInstance:     a.instance,
		HIcon:         win.HICON(icon),
		HCursor:       cursor,
		HbrBackground: win.HBRUSH(win.COLOR_BTNFACE + 1),
		LpszClassName: cn,
		HIconSm:       win.HICON(icon),
	}
	if win.RegisterClassEx(&wc) == 0 {
		return nil, false
	}

	tn, _ := syscall.UTF16PtrFromString(appName)
	a.hwnd = win.CreateWindowEx(0, cn, tn,
		win.WS_OVERLAPPEDWINDOW|win.WS_CLIPCHILDREN,
		win.CW_USEDEFAULT, win.CW_USEDEFAULT,
		a.scaled(1180), a.scaled(800),
		0, 0, a.instance, nil)
	if a.hwnd == 0 {
		return nil, false
	}

	// Re-sync DPI, fonts and controls, then show the window right away so
	// the browser feels instant; the engine fills the rest in a moment.
	if d := dpiOf(a.hwnd); d > 0 && d != int(a.scale*96) {
		a.scale = float64(d) / 96.0
	}

	a.createFonts()
	a.createControls()
	a.createAccelerators()
	a.layout()
	win.ShowWindow(a.hwnd, win.SW_SHOW)
	win.UpdateWindow(a.hwnd)

	if !a.embedWebView() {
		return nil, false
	}

	if startURL != "" {
		a.isStart = false
		a.chromium.Navigate(nav.Parse(startURL))
	} else {
		a.goHome()
	}

	a.chromium.Focus()
	return a, true
}

// Run is the Win32 message loop; it returns when the window is closed.
func (a *app) Run() {
	var msg win.MSG
	for {
		r := win.GetMessage(&msg, 0, 0, 0)
		if r <= 0 {
			break
		}
		// Pressing Enter in the address bar navigates.
		if msg.HWnd == a.address && msg.Message == win.WM_KEYDOWN && msg.WParam == win.VK_RETURN {
			a.navigateFromAddressBar()
			continue
		}
		if translateAccelerator(a.hwnd, a.accel, &msg) != 0 {
			continue
		}
		win.TranslateMessage(&msg)
		win.DispatchMessage(&msg)
	}
}

// loadAppIcon loads the icon embedded by goversioninfo. The application icon
// is stored under resource ID 32512 (IDI_APPLICATION); a fallback chain keeps
// us safe if resource IDs ever shift.
func loadAppIcon(inst win.HINSTANCE) win.HANDLE {
	for _, id := range []uintptr{32512, 2, 1} {
		if h := win.LoadImage(inst, win.MAKEINTRESOURCE(id), win.IMAGE_ICON,
			0, 0, win.LR_DEFAULTSIZE|win.LR_SHARED); h != 0 {
			return h
		}
	}
	return win.LoadImage(0, win.MAKEINTRESOURCE(win.IDI_APPLICATION), win.IMAGE_ICON,
		0, 0, win.LR_DEFAULTSIZE|win.LR_SHARED)
}

func (a *app) createFonts() {
	a.fontUI = makeFont("Segoe UI", a.scaled(13), win.FW_NORMAL)
	a.fontGlyph = makeFont("Segoe MDL2 Assets", a.scaled(16), win.FW_NORMAL)
}

// recreateFonts is called when the DPI changes (e.g. dragging the window
// between monitors) so text stays crisp at every scale.
func (a *app) recreateFonts() {
	if a.fontUI != 0 {
		win.DeleteObject(win.HGDIOBJ(a.fontUI))
	}
	if a.fontGlyph != 0 {
		win.DeleteObject(win.HGDIOBJ(a.fontGlyph))
	}
	a.createFonts()
	for _, c := range []win.HWND{a.back, a.forward, a.reload, a.home, a.goBtn} {
		send(c, win.WM_SETFONT, uintptr(a.fontGlyph), 1)
	}
	send(a.address, win.WM_SETFONT, uintptr(a.fontUI), 1)
}

// makeFont creates a ClearType font for the given point-ish pixel height.
func makeFont(face string, charHeight int32, weight int32) win.HFONT {
	name, err := syscall.UTF16FromString(face)
	if err != nil {
		return 0
	}
	n := len(name)
	if n > 31 {
		n = 31
	}
	lf := win.LOGFONT{
		LfHeight:         -charHeight,
		LfWeight:         weight,
		LfCharSet:        win.DEFAULT_CHARSET,
		LfOutPrecision:   win.OUT_DEFAULT_PRECIS,
		LfClipPrecision:  win.CLIP_DEFAULT_PRECIS,
		LfQuality:        win.CLEARTYPE_QUALITY,
		LfPitchAndFamily: win.DEFAULT_PITCH | win.FF_DONTCARE,
	}
	copy(lf.LfFaceName[:], name[:n])
	return win.CreateFontIndirect(&lf)
}

func (a *app) createControls() {
	a.back = a.button(idcBack, glyphBack)
	a.forward = a.button(idcForward, glyphForward)
	a.reload = a.button(idcReload, glyphReload)
	a.home = a.button(idcHome, glyphHome)
	a.goBtn = a.button(idcGo, glyphGo)

	// Address bar.
	en, _ := syscall.UTF16PtrFromString("Edit")
	a.address = win.CreateWindowEx(win.WS_EX_CLIENTEDGE, en, nil,
		win.WS_CHILD|win.WS_VISIBLE|win.WS_TABSTOP|win.ES_AUTOHSCROLL,
		0, 0, 0, 0, a.hwnd, win.HMENU(idcAddress), a.instance, nil)
	if a.address != 0 {
		sendPtr(a.address, win.EM_SETCUEBANNER, 0, mustUTF16("Search or enter a web address"))
		send(a.address, win.EM_SETLIMITTEXT, 2048, 0)
		send(a.address, win.WM_SETFONT, uintptr(a.fontUI), 1)
	}

	// Host window the WebView2 engine renders into (below the toolbar).
	sn, _ := syscall.UTF16PtrFromString("Static")
	a.host = win.CreateWindowEx(0, sn, nil, win.WS_CHILD|win.WS_VISIBLE,
		0, 0, 0, 0, a.hwnd, win.HMENU(idcHost), a.instance, nil)
}

// button creates one toolbar button with an MDL2 glyph as its caption.
func (a *app) button(id int, glyph string) win.HWND {
	bn, _ := syscall.UTF16PtrFromString("Button")
	gn, _ := syscall.UTF16PtrFromString(glyph)
	h := win.CreateWindowEx(0, bn, gn,
		win.WS_CHILD|win.WS_VISIBLE|win.WS_TABSTOP|win.BS_PUSHBUTTON,
		0, 0, 0, 0, a.hwnd, win.HMENU(id), a.instance, nil)
	if h != 0 {
		send(h, win.WM_SETFONT, uintptr(a.fontGlyph), 1)
	}
	return h
}

func (a *app) createAccelerators() {
	a.accel = createAcceleratorTable([]accel{
		{fVirtKey | fControl, 'L', cmdFocusAddress},
		{fVirtKey | fAlt, 'D', cmdFocusAddress},
		{fVirtKey | fControl, 'N', cmdNewWindow},
		{fVirtKey | fControl, 'T', cmdNewWindow},
		{fVirtKey | fControl, 'W', cmdCloseWindow},
		{fVirtKey | fControl, 'R', cmdReload},
		{fVirtKey, win.VK_F5, cmdReload},
		{fVirtKey | fAlt, win.VK_LEFT, cmdBack},
		{fVirtKey | fAlt, win.VK_RIGHT, cmdForward},
		{fVirtKey | fAlt, win.VK_HOME, cmdHome},
	})
}

// layout positions the toolbar and the web host whenever the window changes
// size. The web engine is told to follow the host window's new rectangle.
func (a *app) layout() {
	if a.hwnd == 0 {
		return
	}
	var rc win.RECT
	if !win.GetClientRect(a.hwnd, &rc) {
		return
	}
	w, h := rc.Right, rc.Bottom
	if w <= 0 || h <= 0 {
		return
	}

	toolbarH := a.scaled(46)
	m := a.scaled(8)
	btnW := a.scaled(40)
	btnH := toolbarH - 2*m

	x := m
	for _, c := range []win.HWND{a.back, a.forward, a.reload, a.home} {
		moveWindow(c, x, m, btnW, btnH)
		x += btnW
	}

	editX := x + m/2
	goW := a.scaled(46)
	editW := w - editX - goW - m
	if editW < a.scaled(60) {
		editW = a.scaled(60)
	}
	moveWindow(a.address, editX, m, editW, btnH)
	moveWindow(a.goBtn, editX+editW+m/2, m, goW, btnH)

	hostH := h - toolbarH
	if hostH < 0 {
		hostH = 0
	}
	moveWindow(a.host, 0, toolbarH, w, hostH)

	if a.chromium != nil {
		a.chromium.Resize()
	}
}

func (a *app) onDpiChanged(dpi int, suggested *win.RECT) {
	if dpi > 0 && int(a.scale*96) != dpi {
		a.scale = float64(dpi) / 96.0
		a.recreateFonts()
	}
	win.SetWindowPos(a.hwnd, 0, suggested.Left, suggested.Top,
		suggested.Right-suggested.Left, suggested.Bottom-suggested.Top,
		win.SWP_NOZORDER|win.SWP_NOACTIVATE)
}

// onCommand handles button clicks and hotkey commands.
func (a *app) onCommand(id int) {
	switch id {
	case idcBack, cmdBack:
		if !a.isStart {
			a.chromium.Eval("history.back()")
		}
	case idcForward, cmdForward:
		if !a.isStart {
			a.chromium.Eval("history.forward()")
		}
	case idcReload, cmdReload:
		if a.isStart {
			a.goHome()
		} else {
			a.chromium.Eval("location.reload()")
		}
	case idcHome, cmdHome:
		a.goHome()
	case idcGo:
		a.navigateFromAddressBar()
	case cmdFocusAddress:
		win.SetFocus(a.address)
		send(a.address, win.EM_SETSEL, 0, ^uintptr(0)) // select all
	case cmdNewWindow:
		spawnNewWindow("")
	case cmdCloseWindow:
		win.DestroyWindow(a.hwnd)
	}
}

// navigateFromAddressBar reads the address bar and navigates.
func (a *app) navigateFromAddressBar() {
	u := nav.Parse(getWindowText(a.address))
	if u == "" {
		a.goHome()
		return
	}
	a.isStart = false
	a.chromium.Navigate(u)
	a.chromium.Focus()
}

// goHome shows the built-in start page.
func (a *app) goHome() {
	a.isStart = true
	setWindowText(a.hwnd, appName)
	setWindowText(a.address, "")
	a.chromium.NavigateToString(nav.StartHTML)
}

// scaled scales a 96-DPI design pixel value to the current DPI.
func (a *app) scaled(v int32) int32 {
	if a.scale == 1 {
		return v
	}
	return int32(float64(v)*a.scale + 0.5)
}

// send sends a window message with plain integer parameters.
func send(hwnd win.HWND, msg uint32, wp, lp uintptr) uintptr {
	return win.SendMessage(hwnd, msg, wp, lp)
}

// sendPtr sends a window message with a pointer-sized parameter.
func sendPtr(hwnd win.HWND, msg uint32, wp uintptr, p *uint16) uintptr {
	if p == nil {
		return 0
	}
	return win.SendMessage(hwnd, msg, wp, uintptr(unsafe.Pointer(p)))
}

// moveWindow is a nil-tolerant MoveWindow.
func moveWindow(hwnd win.HWND, x, y, w, h int32) {
	if hwnd == 0 {
		return
	}
	win.MoveWindow(hwnd, x, y, w, h, true)
}
